#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>

#include "encoder/encoder.hpp"
#include "frontend/logmel.hpp"
#include "gguf/gguf.hpp"
#include "gguf/loader.hpp"

#include <cmath>
#include <fstream>
#include <string>
#include <vector>

using Catch::Approx;

#ifndef ECHOSCRIBE_MODELS_DIR
#define ECHOSCRIBE_MODELS_DIR "models"
#endif

namespace {

std::vector<float> readF32(const std::string& path, size_t expected) {
    std::ifstream f(path, std::ios::binary);
    REQUIRE(f.good());
    f.seekg(0, std::ios::end);
    const size_t bytes = static_cast<size_t>(f.tellg());
    f.seekg(0);
    REQUIRE(bytes == expected * sizeof(float));
    std::vector<float> v(expected);
    f.read(reinterpret_cast<char*>(v.data()), static_cast<std::streamsize>(bytes));
    return v;
}

std::vector<float> syntheticAudio(size_t seconds) {
    std::vector<float> pcm(seconds * 16000);
    for (size_t i = 0; i < pcm.size(); ++i) {
        const double t = static_cast<double>(i) / 16000.0;
        pcm[i] = static_cast<float>(0.3 * std::sin(2.0 * M_PI * 220.0 * t) +
                                    0.2 * std::sin(2.0 * M_PI * 445.0 * t) +
                                    0.15 * std::sin(2.0 * M_PI * 883.0 * t) * std::exp(-t / 2.0) +
                                    0.1 * std::sin(2.0 * M_PI * (300.0 + 50.0 * t) * t) *
                                        std::max(0.0, std::sin(M_PI * t / 2.0)));
    }
    return pcm;
}

bool dataExists(const std::string& path) {
    std::ifstream f(path, std::ios::binary | std::ios::ate);
    return f.good() && f.tellg() > 0;
}

} // namespace

// Reference data (tests/data/*.f32) is generated by running the official
// OpenAI whisper tiny model (converted to f32) in Python; see
// README "Reference data" section. Skipped automatically when absent.
TEST_CASE("encoder matches official whisper reference", "[encoder][model]") {
    const std::string modelPath = ECHOSCRIBE_MODELS_DIR "/whisper-tiny-F16.gguf";
    const std::string melPath = "tests/data/mel_ref.f32";
    const std::string encPath = "tests/data/enc_ref.f32";
    if (!dataExists(modelPath) || !dataExists(melPath) || !dataExists(encPath)) {
        WARN("model or reference data missing, skipping encoder reference test");
        return;
    }

    // 30 s synthetic audio: our log-mel vs whisper's log-mel.
    const auto pcm = syntheticAudio(30);
    auto melOurs = frontend::logMelSpectrogram(pcm.data(), pcm.size());
    auto melRef = readF32(melPath, 80 * 3000);

    double melDiff = 0, melSum = 0;
    for (size_t i = 0; i < melRef.size(); ++i) {
        melDiff = std::max(melDiff, std::abs(static_cast<double>(melOurs.data()[i] - melRef[i])));
        melSum += std::abs(melOurs.data()[i] - melRef[i]);
    }
    INFO("mel max diff = " << melDiff << " mean abs = " << melSum / melRef.size());
    CHECK(melDiff < 5e-3);

    // Encoder on the *reference* mel: isolates encoder math from frontend.
    gguf::File f = gguf::File::open(modelPath);
    whisper::Encoder enc(f);
    REQUIRE(enc.nLayers() == 4);
    REQUIRE(enc.dModel() == 384);
    REQUIRE(enc.nHead() == 6);

    tensor::Tensor melRefT({80, 3000});
    std::copy(melRef.begin(), melRef.end(), melRefT.data());
    tensor::Tensor out = enc.forward(melRefT);
    auto encRef = readF32(encPath, 1500 * 384);
    REQUIRE(out.size() == encRef.size());

    double maxDiff = 0, sumDiff = 0;
    for (size_t i = 0; i < encRef.size(); ++i) {
        maxDiff = std::max(maxDiff, std::abs(static_cast<double>(out.data()[i] - encRef[i])));
        sumDiff += std::abs(out.data()[i] - encRef[i]);
    }
    const double meanDiff = sumDiff / encRef.size();
    INFO("encoder max diff = " << maxDiff << " mean abs = " << meanDiff);
    CHECK(meanDiff < 0.02);
    // f32 accumulation-order noise through 4 transformer layers; the reference
    // itself spans +-17. Relative RMS here is ~0.2%.
    CHECK(maxDiff < 0.35);

    // Encoder on *our* mel: full frontend + encoder chain.
    tensor::Tensor out2 = enc.forward(melOurs);
    double maxDiff2 = 0;
    for (size_t i = 0; i < encRef.size(); ++i) {
        maxDiff2 = std::max(maxDiff2, std::abs(static_cast<double>(out2.data()[i] - encRef[i])));
    }
    INFO("end-to-end max diff = " << maxDiff2);
    CHECK(maxDiff2 < 0.25);
}
