#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>

#include "decoder/decoder.hpp"
#include "encoder/encoder.hpp"
#include "gguf/gguf.hpp"
#include "tokenizer/tokenizer.hpp"

#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#ifndef ECHOSCRIBE_MODELS_DIR
#define ECHOSCRIBE_MODELS_DIR "models"
#endif

namespace {

bool fileExists(const std::string& path) {
    std::ifstream f(path, std::ios::binary | std::ios::ate);
    return f.good() && f.tellg() > 0;
}

std::vector<float> readF32(const std::string& path, size_t expected) {
    std::ifstream f(path, std::ios::binary);
    f.seekg(0, std::ios::end);
    const size_t bytes = static_cast<size_t>(f.tellg());
    f.seekg(0);
    REQUIRE(bytes == expected * sizeof(float));
    std::vector<float> v(expected);
    f.read(reinterpret_cast<char*>(v.data()), static_cast<std::streamsize>(bytes));
    return v;
}

} // namespace

// Golden test: greedy decoding of the jfk.wav sample must reproduce the token
// sequence generated by the official OpenAI whisper tiny model (f32, greedy,
// without timestamps). Skipped automatically when data is missing.
TEST_CASE("decoder reproduces official whisper greedy transcription", "[decoder][model]") {
    const std::string modelPath = ECHOSCRIBE_MODELS_DIR "/whisper-tiny-F16.gguf";
    const std::string melPath = "tests/data/jfk_mel_ref.f32";
    const std::string tokPath = "tests/data/jfk_tokens_ref.txt";
    if (!fileExists(modelPath) || !fileExists(melPath) || !fileExists(tokPath)) {
        WARN("model or reference data missing, skipping decoder test");
        return;
    }

    gguf::File f = gguf::File::open(modelPath);
    whisper::Tokenizer tok(f);
    whisper::Encoder enc(f);
    whisper::Decoder dec(f);
    REQUIRE(dec.nLayers() == 4);
    REQUIRE(dec.nHead() == 6);

    // encoder output from the reference mel (frontend already validated in M4)
    auto melVec = readF32(melPath, 80 * 3000);
    tensor::Tensor mel({80, 3000});
    std::copy(melVec.begin(), melVec.end(), mel.data());
    tensor::Tensor audio = enc.forward(mel);
    REQUIRE(audio.shape() == std::vector<size_t>{1500, 384});

    std::vector<size_t> prompt = {tok.sot(), tok.languageToken("en"), tok.transcribe(),
                                  tok.notimestamps()};
    std::vector<size_t> generated = dec.generate(audio, tok, prompt, /*noTimestamps=*/true, 448);

    // reference sequence read from file
    std::ifstream tf(tokPath);
    std::vector<size_t> ref;
    size_t id;
    while (tf >> id) ref.push_back(id);

    INFO("generated: " << tok.decode(generated));
    INFO("reference: " << tok.decode(ref));

    // exact token match
    REQUIRE(generated == ref);

    // and the decoded text is the famous quote (first token is "ĠAnd",
    // i.e. carries a leading space, exactly like the reference tokens; the
    // official CLI strips it for display)
    REQUIRE(tok.decode(generated) ==
            " And so my fellow Americans ask not what your country can do for you ask what you can "
            "do for your country.");
}

// Same, but with timestamps enabled: exercises the full ApplyTimestampRules
// (pairs, monotonicity, max_initial_timestamp, timestamp-vs-text probability).
TEST_CASE("decoder with timestamps matches official whisper", "[decoder][model]") {
    const std::string modelPath = ECHOSCRIBE_MODELS_DIR "/whisper-tiny-F16.gguf";
    const std::string melPath = "tests/data/jfk_mel_ref.f32";
    const std::string tokPath = "tests/data/jfk_tokens_ref_ts.txt";
    if (!fileExists(modelPath) || !fileExists(melPath) || !fileExists(tokPath)) {
        WARN("model or reference data missing, skipping timestamped decoder test");
        return;
    }

    gguf::File f = gguf::File::open(modelPath);
    whisper::Tokenizer tok(f);
    whisper::Encoder enc(f);
    whisper::Decoder dec(f);

    auto melVec = readF32(melPath, 80 * 3000);
    tensor::Tensor mel({80, 3000});
    std::copy(melVec.begin(), melVec.end(), mel.data());
    tensor::Tensor audio = enc.forward(mel);

    std::vector<size_t> prompt = {tok.sot(), tok.languageToken("en"), tok.transcribe()};
    std::vector<size_t> generated = dec.generate(audio, tok, prompt, /*noTimestamps=*/false, 448);

    std::ifstream tf(tokPath);
    std::vector<size_t> ref;
    size_t id;
    while (tf >> id) ref.push_back(id);

    INFO("generated: " << tok.decode(generated));
    INFO("reference: " << tok.decode(ref));
    REQUIRE(generated == ref);

    // timestamps: first token is <|0.00|>, last is the segment end
    REQUIRE(generated.front() == tok.timestampBegin());
    REQUIRE(generated.back() >= tok.timestampBegin());
    REQUIRE(tok.timestampSeconds(generated.back()) == Catch::Approx(10.5).margin(1e-9));
}
